---
name: Lint codebase

on:  # yamllint disable-line rule:truthy
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    paths-ignore:
      - '**/*.md'
      - '**/Dockerfile.*'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/Dockerfile.*'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set reviewdog reporter type
        run: |
          if [ ${{ github.event_name }} != "pull_request" ]; then
            echo "REVIEWDOG_REPORTER=local" >> $GITHUB_ENV
          else
            echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          fi

      - name: Lint PHP
        uses: shirobrak/action-phpcs@v1.5.0
        with:
          reporter: ${{ env.REVIEWDOG_REPORTER }}
          level: info
          filter_mode: nofilter
          fail_on_error: true
          phpcs_flags: --standard=PSR12
